### ISSUE TITLE
The bito Cannot Connect ,What Happened?

### ISSUE THREAD

**Issue by Hoper-Q** [gitbito/bitoai#144]
Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state

Load web wrong ,what happened?

**Comment by bitoandy** [comment]
hi @Hoper-Q ,

We are looking into this, can you provide more details to help us debug the issue.

**Comment by bitoandy** [comment]
Also can you restart your IDE to check if the issue is now resolved.

**Comment by nisha-bito** [comment]
hi @Hoper-Q ,

Please suggest of you are still facing issue or you are able to load Bito now.

Thanks,
Nisha

**Comment by Hoper-Q** [comment]
> hi @Hoper-Q ,
> 
> Please suggest of you are still facing issue or you are able to load Bito now.
> 
> Thanks, Nisha

Well
Now there is no problem.
I think it`s may device have something wrong or other things.
But in that time, I actually Can`t use it with the same wrong.

**Comment by nisha-bito** [comment]
Great to hear that you are able to load Bito now.

Sometime, VS code doesn't load plugin properly due to cache. You can also hit command ctrl + shift + P -> Type "Developer: Reload windows" and hit enter. Restart VS code , in case you face this issue later sometime.

Thanks,
Nisha
